swagger: "2.0"
info:
  description: "A API about the results of the feedbacks"
  version: "1.0.0"
  title: "Feedbacks results"
  termsOfService: "http://helloreverb.com/terms/"
  contact:
    name: "Swagger API team"
    url: "http://swagger.io"
    email: "foo@example.com"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /feedbacksInformation:
    post:
      description: "Creates a new feedback.  Duplicates are allowed"
      operationId: "addFeedback"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "feedback"
        description: "Feedback to add"
        required: true
        schema:
          $ref: "#/definitions/feedbackInformation"
      responses:
        200:
          description: "feedback response"
          schema:
            $ref: "#/definitions/feedbackInformation"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
  /feedbacksInformation/{idFeedback}:
    get:
      description: "Returns the information of a feedback based on a single ID"
      operationId: "findFeedbackById"
      produces:
      - "application/json"
      - "application/xml"
      - "text/xml"
      - "text/html"
      parameters:
      - name: "idFeedback"
        in: "path"
        description: "ID of feedback to fetch"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "pet response"
          schema:
            $ref: "#/definitions/feedbackInformation"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
    delete:
      description: "deletes a single feedback based on the ID supplied"
      operationId: "deleteFeedback"
      parameters:
      - name: "idFeedback"
        in: "path"
        description: "ID of feedback to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "feedback deleted"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
definitions:
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  feedbackInformation:
    type: "object"
    properties:
      idFeedback:
        type: "integer"
        format: "int32"
      preparation:
        type: "array"
        items:
          $ref: "#/definitions/preparation"
      checks:
        type: "array"
        items:
          $ref: "#/definitions/check"
  preparation:
    type: "object"
    properties:
      idPreparation:
        type: "integer"
        format: "int32"
      description:
        type: "string"
  check:
    type: "object"
    properties:
      idCheck:
        type: "integer"
        format: "int32"
      typeCheck:
        type: "string"
      description:
        type: "string"
